name: Newman Run

on:
  pull_request:
    branches:
    - main

jobs:

  bash-example:
    runs-on: ubuntu-latest
    steps:
        - name: Group of log lines
          run: |
              echo "::group::My title"
              echo "Inside group"
              echo "::endgroup::"
              echo "github.event.head_commit.message"
            
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection:  .github/workflows/ETOS_APP_OCAPI.postman_collection.json
          environment: .github/workflows/DEV.postman_environment.json
          envVar: '[{ "key": "CLIENT_SECRET", "value": "${{ secrets.SFCC_ETOSDEV_CLIENT_SECRET }}" }]'
