name: Newman Run

on: workflow_dispatch

jobs:

  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: .github/workflows/ETOS_APP_OCAPI.postman_collection.json
          folder: '["TESTS"]'
          environment: .github/workflows/DEV.postman_environment.json
          envVar: '[{ "key": "CLIENT_SECRET", "value": "${{ secrets.SFCC_ETOSDEV_CLIENT_SECRET }}" }, { "key": "ADYEN_X_API_KEY", "value": "${{ secrets.ADYEN_X_API_KEY }}" }]'

      
      - uses: iurii.bazhan@gmail.com
        with:
          to: your@email.com
          subject: Postman Test Results
          message: |
            The Postman test results are attached.
