name: Newman Run

on:
  pull_request:
    branches:
    - main

jobs:
            
  newman:
    runs-on: ubuntu-latest
    if: "${{ contains(toJSON(github.event.pull_request.title), 'OCAPI') }}"
    steps:
      - name: Print commit message
        run: |
          echo "${{toJSON(github.event.pull_request.title)}}"
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection:  .github/workflows/ETOS_APP_OCAPI.postman_collection.json --folder "TESTS"
          environment: .github/workflows/DEV.postman_environment.json
          envVar: '[{ "key": "CLIENT_SECRET", "value": "${{ secrets.SFCC_ETOSDEV_CLIENT_SECRET }}" }]'
